// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Download.proto

package com.cooyet.im.protobuf;

public final class IMDownload {
  private IMDownload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IMDownloadReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Download.IMDownloadReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint32 task_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0c01
     * </pre>
     */
    boolean hasTaskId();
    /**
     * <code>required uint32 task_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0c01
     * </pre>
     */
    int getTaskId();

    /**
     * <code>required uint32 sequence_id = 2;</code>
     *
     * <pre>
     *序号
     * </pre>
     */
    boolean hasSequenceId();
    /**
     * <code>required uint32 sequence_id = 2;</code>
     *
     * <pre>
     *序号
     * </pre>
     */
    int getSequenceId();

    /**
     * <code>required uint32 download_time = 3;</code>
     *
     * <pre>
     *上传时间
     * </pre>
     */
    boolean hasDownloadTime();
    /**
     * <code>required uint32 download_time = 3;</code>
     *
     * <pre>
     *上传时间
     * </pre>
     */
    int getDownloadTime();
  }
  /**
   * Protobuf type {@code IM.Download.IMDownloadReq}
   */
  public static final class IMDownloadReq extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:IM.Download.IMDownloadReq)
      IMDownloadReqOrBuilder {
    // Use IMDownloadReq.newBuilder() to construct.
    private IMDownloadReq(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMDownloadReq(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMDownloadReq defaultInstance;
    public static IMDownloadReq getDefaultInstance() {
      return defaultInstance;
    }

    public IMDownloadReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMDownloadReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              taskId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sequenceId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              downloadTime_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMDownloadReq> PARSER =
        new com.google.protobuf.AbstractParser<IMDownloadReq>() {
      public IMDownloadReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMDownloadReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IMDownloadReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TASK_ID_FIELD_NUMBER = 1;
    private int taskId_;
    /**
     * <code>required uint32 task_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0c01
     * </pre>
     */
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 task_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0c01
     * </pre>
     */
    public int getTaskId() {
      return taskId_;
    }

    public static final int SEQUENCE_ID_FIELD_NUMBER = 2;
    private int sequenceId_;
    /**
     * <code>required uint32 sequence_id = 2;</code>
     *
     * <pre>
     *序号
     * </pre>
     */
    public boolean hasSequenceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 sequence_id = 2;</code>
     *
     * <pre>
     *序号
     * </pre>
     */
    public int getSequenceId() {
      return sequenceId_;
    }

    public static final int DOWNLOAD_TIME_FIELD_NUMBER = 3;
    private int downloadTime_;
    /**
     * <code>required uint32 download_time = 3;</code>
     *
     * <pre>
     *上传时间
     * </pre>
     */
    public boolean hasDownloadTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 download_time = 3;</code>
     *
     * <pre>
     *上传时间
     * </pre>
     */
    public int getDownloadTime() {
      return downloadTime_;
    }

    private void initFields() {
      taskId_ = 0;
      sequenceId_ = 0;
      downloadTime_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTaskId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSequenceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDownloadTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, taskId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, sequenceId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, downloadTime_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, taskId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, sequenceId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, downloadTime_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cooyet.im.protobuf.IMDownload.IMDownloadReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cooyet.im.protobuf.IMDownload.IMDownloadReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code IM.Download.IMDownloadReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.cooyet.im.protobuf.IMDownload.IMDownloadReq, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:IM.Download.IMDownloadReq)
        com.cooyet.im.protobuf.IMDownload.IMDownloadReqOrBuilder {
      // Construct using com.cooyet.im.protobuf.IMDownload.IMDownloadReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        taskId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sequenceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        downloadTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.cooyet.im.protobuf.IMDownload.IMDownloadReq getDefaultInstanceForType() {
        return com.cooyet.im.protobuf.IMDownload.IMDownloadReq.getDefaultInstance();
      }

      public com.cooyet.im.protobuf.IMDownload.IMDownloadReq build() {
        com.cooyet.im.protobuf.IMDownload.IMDownloadReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cooyet.im.protobuf.IMDownload.IMDownloadReq buildPartial() {
        com.cooyet.im.protobuf.IMDownload.IMDownloadReq result = new com.cooyet.im.protobuf.IMDownload.IMDownloadReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.taskId_ = taskId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sequenceId_ = sequenceId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.downloadTime_ = downloadTime_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.cooyet.im.protobuf.IMDownload.IMDownloadReq other) {
        if (other == com.cooyet.im.protobuf.IMDownload.IMDownloadReq.getDefaultInstance()) return this;
        if (other.hasTaskId()) {
          setTaskId(other.getTaskId());
        }
        if (other.hasSequenceId()) {
          setSequenceId(other.getSequenceId());
        }
        if (other.hasDownloadTime()) {
          setDownloadTime(other.getDownloadTime());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTaskId()) {
          
          return false;
        }
        if (!hasSequenceId()) {
          
          return false;
        }
        if (!hasDownloadTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cooyet.im.protobuf.IMDownload.IMDownloadReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cooyet.im.protobuf.IMDownload.IMDownloadReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int taskId_ ;
      /**
       * <code>required uint32 task_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0c01
       * </pre>
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 task_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0c01
       * </pre>
       */
      public int getTaskId() {
        return taskId_;
      }
      /**
       * <code>required uint32 task_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0c01
       * </pre>
       */
      public Builder setTaskId(int value) {
        bitField0_ |= 0x00000001;
        taskId_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 task_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0c01
       * </pre>
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        taskId_ = 0;
        
        return this;
      }

      private int sequenceId_ ;
      /**
       * <code>required uint32 sequence_id = 2;</code>
       *
       * <pre>
       *序号
       * </pre>
       */
      public boolean hasSequenceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 sequence_id = 2;</code>
       *
       * <pre>
       *序号
       * </pre>
       */
      public int getSequenceId() {
        return sequenceId_;
      }
      /**
       * <code>required uint32 sequence_id = 2;</code>
       *
       * <pre>
       *序号
       * </pre>
       */
      public Builder setSequenceId(int value) {
        bitField0_ |= 0x00000002;
        sequenceId_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 sequence_id = 2;</code>
       *
       * <pre>
       *序号
       * </pre>
       */
      public Builder clearSequenceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sequenceId_ = 0;
        
        return this;
      }

      private int downloadTime_ ;
      /**
       * <code>required uint32 download_time = 3;</code>
       *
       * <pre>
       *上传时间
       * </pre>
       */
      public boolean hasDownloadTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 download_time = 3;</code>
       *
       * <pre>
       *上传时间
       * </pre>
       */
      public int getDownloadTime() {
        return downloadTime_;
      }
      /**
       * <code>required uint32 download_time = 3;</code>
       *
       * <pre>
       *上传时间
       * </pre>
       */
      public Builder setDownloadTime(int value) {
        bitField0_ |= 0x00000004;
        downloadTime_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 download_time = 3;</code>
       *
       * <pre>
       *上传时间
       * </pre>
       */
      public Builder clearDownloadTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        downloadTime_ = 0;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Download.IMDownloadReq)
    }

    static {
      defaultInstance = new IMDownloadReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Download.IMDownloadReq)
  }

  public interface IMDownloadResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Download.IMDownloadRes)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint32 task_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0c02
     * </pre>
     */
    boolean hasTaskId();
    /**
     * <code>required uint32 task_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0c02
     * </pre>
     */
    int getTaskId();

    /**
     * <code>required uint32 sequence_id = 2;</code>
     *
     * <pre>
     *序号
     * </pre>
     */
    boolean hasSequenceId();
    /**
     * <code>required uint32 sequence_id = 2;</code>
     *
     * <pre>
     *序号
     * </pre>
     */
    int getSequenceId();

    /**
     * <code>required bytes data = 3;</code>
     *
     * <pre>
     *数据
     * </pre>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 3;</code>
     *
     * <pre>
     *数据
     * </pre>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code IM.Download.IMDownloadRes}
   */
  public static final class IMDownloadRes extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:IM.Download.IMDownloadRes)
      IMDownloadResOrBuilder {
    // Use IMDownloadRes.newBuilder() to construct.
    private IMDownloadRes(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMDownloadRes(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMDownloadRes defaultInstance;
    public static IMDownloadRes getDefaultInstance() {
      return defaultInstance;
    }

    public IMDownloadRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMDownloadRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              taskId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sequenceId_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMDownloadRes> PARSER =
        new com.google.protobuf.AbstractParser<IMDownloadRes>() {
      public IMDownloadRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMDownloadRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IMDownloadRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TASK_ID_FIELD_NUMBER = 1;
    private int taskId_;
    /**
     * <code>required uint32 task_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0c02
     * </pre>
     */
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 task_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0c02
     * </pre>
     */
    public int getTaskId() {
      return taskId_;
    }

    public static final int SEQUENCE_ID_FIELD_NUMBER = 2;
    private int sequenceId_;
    /**
     * <code>required uint32 sequence_id = 2;</code>
     *
     * <pre>
     *序号
     * </pre>
     */
    public boolean hasSequenceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 sequence_id = 2;</code>
     *
     * <pre>
     *序号
     * </pre>
     */
    public int getSequenceId() {
      return sequenceId_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 3;</code>
     *
     * <pre>
     *数据
     * </pre>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes data = 3;</code>
     *
     * <pre>
     *数据
     * </pre>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      taskId_ = 0;
      sequenceId_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTaskId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSequenceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, taskId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, sequenceId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, data_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, taskId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, sequenceId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cooyet.im.protobuf.IMDownload.IMDownloadRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDownloadRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cooyet.im.protobuf.IMDownload.IMDownloadRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code IM.Download.IMDownloadRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.cooyet.im.protobuf.IMDownload.IMDownloadRes, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:IM.Download.IMDownloadRes)
        com.cooyet.im.protobuf.IMDownload.IMDownloadResOrBuilder {
      // Construct using com.cooyet.im.protobuf.IMDownload.IMDownloadRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        taskId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sequenceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.cooyet.im.protobuf.IMDownload.IMDownloadRes getDefaultInstanceForType() {
        return com.cooyet.im.protobuf.IMDownload.IMDownloadRes.getDefaultInstance();
      }

      public com.cooyet.im.protobuf.IMDownload.IMDownloadRes build() {
        com.cooyet.im.protobuf.IMDownload.IMDownloadRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cooyet.im.protobuf.IMDownload.IMDownloadRes buildPartial() {
        com.cooyet.im.protobuf.IMDownload.IMDownloadRes result = new com.cooyet.im.protobuf.IMDownload.IMDownloadRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.taskId_ = taskId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sequenceId_ = sequenceId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.cooyet.im.protobuf.IMDownload.IMDownloadRes other) {
        if (other == com.cooyet.im.protobuf.IMDownload.IMDownloadRes.getDefaultInstance()) return this;
        if (other.hasTaskId()) {
          setTaskId(other.getTaskId());
        }
        if (other.hasSequenceId()) {
          setSequenceId(other.getSequenceId());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTaskId()) {
          
          return false;
        }
        if (!hasSequenceId()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cooyet.im.protobuf.IMDownload.IMDownloadRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cooyet.im.protobuf.IMDownload.IMDownloadRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int taskId_ ;
      /**
       * <code>required uint32 task_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0c02
       * </pre>
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 task_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0c02
       * </pre>
       */
      public int getTaskId() {
        return taskId_;
      }
      /**
       * <code>required uint32 task_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0c02
       * </pre>
       */
      public Builder setTaskId(int value) {
        bitField0_ |= 0x00000001;
        taskId_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 task_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0c02
       * </pre>
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        taskId_ = 0;
        
        return this;
      }

      private int sequenceId_ ;
      /**
       * <code>required uint32 sequence_id = 2;</code>
       *
       * <pre>
       *序号
       * </pre>
       */
      public boolean hasSequenceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 sequence_id = 2;</code>
       *
       * <pre>
       *序号
       * </pre>
       */
      public int getSequenceId() {
        return sequenceId_;
      }
      /**
       * <code>required uint32 sequence_id = 2;</code>
       *
       * <pre>
       *序号
       * </pre>
       */
      public Builder setSequenceId(int value) {
        bitField0_ |= 0x00000002;
        sequenceId_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 sequence_id = 2;</code>
       *
       * <pre>
       *序号
       * </pre>
       */
      public Builder clearSequenceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sequenceId_ = 0;
        
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 3;</code>
       *
       * <pre>
       *数据
       * </pre>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes data = 3;</code>
       *
       * <pre>
       *数据
       * </pre>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 3;</code>
       *
       * <pre>
       *数据
       * </pre>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        
        return this;
      }
      /**
       * <code>required bytes data = 3;</code>
       *
       * <pre>
       *数据
       * </pre>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Download.IMDownloadRes)
    }

    static {
      defaultInstance = new IMDownloadRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Download.IMDownloadRes)
  }

  public interface IMDeleteTaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Download.IMDeleteTask)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint32 task_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0c03
     * </pre>
     */
    boolean hasTaskId();
    /**
     * <code>required uint32 task_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0c03
     * </pre>
     */
    int getTaskId();
  }
  /**
   * Protobuf type {@code IM.Download.IMDeleteTask}
   */
  public static final class IMDeleteTask extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:IM.Download.IMDeleteTask)
      IMDeleteTaskOrBuilder {
    // Use IMDeleteTask.newBuilder() to construct.
    private IMDeleteTask(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMDeleteTask(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMDeleteTask defaultInstance;
    public static IMDeleteTask getDefaultInstance() {
      return defaultInstance;
    }

    public IMDeleteTask getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMDeleteTask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              taskId_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMDeleteTask> PARSER =
        new com.google.protobuf.AbstractParser<IMDeleteTask>() {
      public IMDeleteTask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMDeleteTask(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IMDeleteTask> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TASK_ID_FIELD_NUMBER = 1;
    private int taskId_;
    /**
     * <code>required uint32 task_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0c03
     * </pre>
     */
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 task_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0c03
     * </pre>
     */
    public int getTaskId() {
      return taskId_;
    }

    private void initFields() {
      taskId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTaskId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, taskId_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, taskId_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cooyet.im.protobuf.IMDownload.IMDeleteTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDeleteTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDeleteTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDeleteTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDeleteTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDeleteTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDeleteTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDeleteTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDeleteTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cooyet.im.protobuf.IMDownload.IMDeleteTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cooyet.im.protobuf.IMDownload.IMDeleteTask prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code IM.Download.IMDeleteTask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.cooyet.im.protobuf.IMDownload.IMDeleteTask, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:IM.Download.IMDeleteTask)
        com.cooyet.im.protobuf.IMDownload.IMDeleteTaskOrBuilder {
      // Construct using com.cooyet.im.protobuf.IMDownload.IMDeleteTask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        taskId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.cooyet.im.protobuf.IMDownload.IMDeleteTask getDefaultInstanceForType() {
        return com.cooyet.im.protobuf.IMDownload.IMDeleteTask.getDefaultInstance();
      }

      public com.cooyet.im.protobuf.IMDownload.IMDeleteTask build() {
        com.cooyet.im.protobuf.IMDownload.IMDeleteTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cooyet.im.protobuf.IMDownload.IMDeleteTask buildPartial() {
        com.cooyet.im.protobuf.IMDownload.IMDeleteTask result = new com.cooyet.im.protobuf.IMDownload.IMDeleteTask(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.taskId_ = taskId_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.cooyet.im.protobuf.IMDownload.IMDeleteTask other) {
        if (other == com.cooyet.im.protobuf.IMDownload.IMDeleteTask.getDefaultInstance()) return this;
        if (other.hasTaskId()) {
          setTaskId(other.getTaskId());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTaskId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cooyet.im.protobuf.IMDownload.IMDeleteTask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cooyet.im.protobuf.IMDownload.IMDeleteTask) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int taskId_ ;
      /**
       * <code>required uint32 task_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0c03
       * </pre>
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 task_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0c03
       * </pre>
       */
      public int getTaskId() {
        return taskId_;
      }
      /**
       * <code>required uint32 task_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0c03
       * </pre>
       */
      public Builder setTaskId(int value) {
        bitField0_ |= 0x00000001;
        taskId_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 task_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0c03
       * </pre>
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        taskId_ = 0;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Download.IMDeleteTask)
    }

    static {
      defaultInstance = new IMDeleteTask(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Download.IMDeleteTask)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
